### ISSUE TITLE
Change compilation config to CMake

### ISSUE THREAD

**Issue by umgefahren** [matteolutz/Umber#1]
I would like the project for myself, but I use a computer without Visual Studio installed. Maybe consider switching to the CMake + Ninja Build system, because this would make your Project more portable.

In this instance consider using GitHub Actions.

**Comment by matteolutz** [comment]
Hello Hannes, I'm currently working on a different build system, that's also faster than VS. I'm thinking of something like cmake and premake. It will be changed very soon...
